'use client';
import { Inter } from "next/font/google";
import "./globals.css";
import '@floating-ui/react';
import 'bootstrap/dist/css/bootstrap.min.css';
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(()=>{
    
  })
  return (
    <html lang="en">
      
      
      <body className={inter.className}>
      <nav className="navbar navbar-expand-lg bg-dark">
        <div className="container-fluid">
          
          <button className="navbar-toggler text-white bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav ">
              <li className="nav-item">
                <a className="nav-link active text-white" aria-current="page" href="/clients">Clientes</a>
              </li>
              <li className="nav-item">
                <a className="nav-link text-white" href="/products">Productos</a>
              </li>
              <li className="nav-item">
                <a className="nav-link text-white" href="/orders">Pedidos</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div className="d-flex justify-content-center">
      <div className="d-flex justify-content-center mt-4">
          <h1></h1>
        </div>
      </div>
      
        {children}
        </body>
      
      
    </html>
  );
}
